version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flightdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    env_file:
      - ../backend/.env
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/flightdb
      - ENV=dev
      # SEED_* берутся из env_file (.env.example -> скопируй в .env и измени пароли в реальной среде)
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    environment:
  # For local dev keep pointing to backend container; override in prod build env
  - VITE_API_BASE=http://localhost:8000
    depends_on:
      - backend

volumes:
  db_data:
