version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flightdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    env_file:
      - ../backend/.env.example
    environment:
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/flightdb
      - ENV=dev
      - SEED_ADMIN_EMAIL=admin@demo.local
      - SEED_ADMIN_PASSWORD=Admin1234!
      - SEED_MANAGER_EMAIL=manager@demo.local
      - SEED_MANAGER_PASSWORD=Manager1234!
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:8000
    depends_on:
      - backend

volumes:
  db_data:
